import StandardPageSection from '@/Components/PageSections/StandardPageSection';
import Hero from '../Components/Hero/Hero';
import ImagePageSection from '@/Components/PageSections/ImagePageSection';

export default function BatteryStoragePage() {
  return (
    <div>
      <Hero src="/images/bat/bat1.jpeg">
        <h1>Battery Storage</h1>
      </Hero>
      <StandardPageSection
        data={{
          title: '',
          text: [
            'We take pride in offering a variety of state-of-the-art batteries that perfectly complement your panel system. Our solar batteries provide an eco-efficient solution for storing any solar energy generated by your panels. Let’s delve into the world of batteries, explore their benefits, and discover how we can help you achieve energy independence.',
          ],
        }}
      />
      <div className="flex-container">
        <div className="item">
          <h3>Energy Independence</h3>
          <p>
            Energy independence is a compelling benefit of solar batteries, and
            it represents a transformative shift in the way individuals and
            businesses consume electricity.
          </p>
        </div>
        <div className="item">
          <h3>Continuous Power Supply</h3>
          <p>
            We have the ability to instal a plug socked that leads directly to
            your solar panel batteries. Meaning, in the event of a power outage,
            you can still power your essential devices from the power stored in
            your batteries.
          </p>
        </div>
        <div className="item">
          <h3>Become Less Dependant on the National Grid</h3>
          <p>
            By using batteries, you can reduce dependence on the grid and
            therefore have more control over your energy consumption and
            expenses. This means that you can power your home during grid
            outages, disruptions, or fluctuations in energy supply.
          </p>
        </div>
      </div>
      <ImagePageSection
        data={{
          image: { url: '/images/bat/bat2.jpeg' },
          title: '',
          content: {
            html: ``,
          },
        }}
      />
      <div className="why-choose">
        <h2>Why Choose Total Green Energy Solutions</h2>
        <p>
          When you choose Total Green Energy Solutions, you're choosing a
          partner you can trust to deliver high-quality solar solutions that
          meet your needs, save you money, and help create a more sustainable
          future for our planet.
        </p>
      </div>
    </div>
  );
}
